parser: babel-eslint
env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: [
    eslint:recommended,
    plugin:react/recommended
  ]

parserOptions:
  ecmaFeatures:
    {
      arrowFunctions: true,
      blockBindings: true,
      classes: true,
      defaultParams: true,
      destructuring: true,
      forOf: true,
      generators: false,
      modules: true,
      objectLiteralComputedProperties: true,
      objectLiteralDuplicateProperties: false,
      objectLiteralShorthandMethods: true,
      objectLiteralShorthandProperties: true,
      restParams: true,
      spread: true,
      superInFunctions: true,
      templateStrings: true,
      jsx: true
    }
  ecmaVersion: 6
  sourceType: module

plugins: [
  react
]

settings:
  react:
    version: detect
